// ── Job Categories ─────────────────────────────────────────────────────────────
// Matches backend enum: development | marketing | sales | design | consultancy

export const JOB_CATEGORY_OPTIONS = [
  "Development",
  "Marketing",
  "Sales",
  "Design",
  "Consultancy",
];

// Maps display label → backend enum value
export const JOB_CATEGORY_API_MAP = {
  Development: "development",
  Marketing: "marketing",
  Sales: "sales",
  Design: "design",
  Consultancy: "consultancy",
};

// ── Job Roles by Category ──────────────────────────────────────────────────────
// Used as reference for role titles per category

export const JOB_ROLES_BY_CATEGORY = {
  Development: [
    "Frontend Developer",
    "Backend Developer",
    "Full Stack Developer",
    "Web Developer",
    "Mobile App Developer (iOS/Android)",
    "Software Engineer",
    "Software Developer",
    "Application Developer",
    "Game Developer",
    "Embedded Systems Developer",
    "Data Scientist",
    "Data Analyst",
    "Data Engineer",
    "Machine Learning Engineer",
    "AI Engineer",
    "Computer Vision Engineer",
    "NLP Engineer",
    "MLOps Engineer",
    "DevOps Engineer",
    "Site Reliability Engineer (SRE)",
    "Cloud Engineer",
    "Cloud Architect",
    "Platform Engineer",
    "Infrastructure Engineer",
    "Cybersecurity Analyst",
    "Security Engineer",
    "Network Engineer",
    "Systems Engineer",
    "IT Support Specialist",
    "IT Administrator",
    "QA Engineer",
    "Software Tester",
    "Automation Test Engineer",
    "Performance Test Engineer",
    "Blockchain Developer",
    "AR/VR Developer",
  ],
  Marketing: [
    "Digital Marketing Specialist",
    "SEO Specialist",
    "Content Strategist",
    "Social Media Manager",
    "Growth Hacker / Growth Marketer",
  ],
  Sales: [
    "Sales Executive (Tech Sales / SaaS Sales)",
    "Business Development Executive",
    "Solutions Engineer / Pre-Sales Engineer",
  ],
  Design: [
    "UI Designer",
    "UX Designer",
    "Product Designer",
    "Graphic Designer",
  ],
  Consultancy: [
    "Product Manager",
    "Technical Product Manager",
    "Developer Advocate",
    "Technical Writer",
  ],
};

// ── Technical Skills by Category ───────────────────────────────────────────────
// Shown as suggestions in the Technical Skills field based on selected category

export const TECH_SKILLS_BY_CATEGORY = {
  Development: [
    "JavaScript",
    "TypeScript",
    "React",
    "Next.js",
    "Node.js",
    "Python",
    "Java",
    "Go",
    "C++",
    "C#",
    "SQL",
    "Git",
    "Docker",
    "Kubernetes",
    "AWS",
    "GCP",
    "Azure",
    "REST APIs",
    "GraphQL",
    "MongoDB",
    "PostgreSQL",
    "Redis",
    "CI/CD",
    "Microservices",
    "System Design",
    "Linux",
    "Terraform",
    "React Native",
    "Flutter",
    "TensorFlow",
    "PyTorch",
  ],
  Marketing: [
    "Google Ads",
    "Meta Ads",
    "LinkedIn Ads",
    "SEO",
    "Google Analytics",
    "A/B Testing",
    "Content Marketing",
    "Email Marketing",
    "Social Media Marketing",
    "Copywriting",
    "Conversion Tracking",
    "HubSpot",
    "Funnel Optimisation",
    "Semrush",
    "Canva",
    "Excel / Google Sheets",
    "Marketing Automation",
  ],
  Sales: [
    "CRM (Salesforce / HubSpot)",
    "Lead Generation",
    "Cold Calling",
    "Cold Emailing",
    "B2B Sales",
    "SaaS Sales",
    "Sales Forecasting",
    "Pipeline Management",
    "Negotiation",
    "Prospecting",
    "Account Management",
    "Product Demo",
    "LinkedIn Sales Navigator",
    "Excel / Google Sheets",
  ],
  Design: [
    "Figma",
    "Adobe XD",
    "Sketch",
    "Adobe Photoshop",
    "Adobe Illustrator",
    "Prototyping",
    "User Research",
    "Wireframing",
    "Design Systems",
    "Motion Design",
    "After Effects",
    "Zeplin",
    "InVision",
    "Typography",
    "Colour Theory",
  ],
  Consultancy: [
    "Business Analysis",
    "Project Management",
    "Stakeholder Management",
    "Data Analysis",
    "Strategy Consulting",
    "Process Improvement",
    "Change Management",
    "Risk Management",
    "Excel / Google Sheets",
    "PowerPoint",
    "Agile",
    "JIRA",
    "Client Presentation",
    "Problem Solving",
    "Technical Writing",
  ],
};

// ── Strategic Skills by Category ───────────────────────────────────────────────
// Shown as suggestions in the Strategic Skills field based on selected category

export const STRATEGIC_SKILLS_BY_CATEGORY = {
  Development: [
    "Problem Solving",
    "Analytical Thinking",
    "System Design Thinking",
    "Communication",
    "Team Collaboration",
    "Agile Mindset",
    "Code Review",
    "Mentoring",
    "Technical Leadership",
    "Attention to Detail",
    "Ownership & Accountability",
  ],
  Marketing: [
    "Consumer Psychology",
    "Creative Thinking",
    "Growth Strategy",
    "Campaign Management",
    "Communication",
    "Analytical Thinking",
    "Brand Storytelling",
    "Audience Research",
    "Strategic Planning",
    "Data-Driven Decision Making",
  ],
  Sales: [
    "Negotiation",
    "Persuasion",
    "Relationship Building",
    "Communication",
    "Goal Orientation",
    "Resilience",
    "Time Management",
    "Strategic Thinking",
    "Customer Focus",
    "Objection Handling",
  ],
  Design: [
    "Creative Thinking",
    "Visual Storytelling",
    "User Empathy",
    "Problem Solving",
    "Attention to Detail",
    "Communication",
    "Collaboration",
    "Design Thinking",
    "Aesthetic Sensibility",
    "Feedback Receptiveness",
  ],
  Consultancy: [
    "Strategic Thinking",
    "Problem Solving",
    "Communication",
    "Leadership",
    "Stakeholder Management",
    "Analytical Thinking",
    "Change Management",
    "Decision Making",
    "Presentation Skills",
    "Business Acumen",
  ],
};
